In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Importation de données complémentaire (En pause): 

Sommes nous en train de tricher ? C'est en tout cas pas interdit...

In [3]:
files = ['22-23.csv', '13-14.csv', '14-15.csv', '15-16.csv', '16-17.csv', '17-18.csv', '18-19.csv', '19-20.csv', '20-21.csv', '21-22.csv']
dir_path = 'Odds data L1\\'
dfs = [pd.read_csv(dir_path + file) for file in files]
df = pd.concat(dfs, ignore_index=True)

#On veut trier par date.
df['Date']

def parse_date(date_str):
    try:
        return pd.to_datetime(date_str, format='%d/%m/%y')
    except ValueError:
        return pd.to_datetime(date_str, format='%d/%m/%Y')
    
df['Date'] = df['Date'].apply(parse_date)
df.sort_values('Date', inplace=True)
df

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbMx>2.5,BbAv>2.5,BbMx<2.5,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA
380,F1,2013-08-09,NaN,Montpellier,Paris SG,1.0,1.0,D,1.0,0.0,...,2.20,2.10,1.82,1.71,15.0,0.50,2.13,2.07,1.85,1.78
387,F1,2013-08-10,NaN,Valenciennes,Toulouse,3.0,0.0,H,1.0,0.0,...,2.45,2.25,1.69,1.57,17.0,0.00,1.84,1.80,2.11,2.04
386,F1,2013-08-10,NaN,Rennes,Reims,2.0,1.0,H,1.0,1.0,...,2.30,2.14,1.80,1.70,18.0,-0.50,1.80,1.73,2.21,2.15
385,F1,2013-08-10,NaN,Nantes,Bastia,2.0,0.0,H,1.0,0.0,...,2.25,2.17,1.80,1.66,17.0,-0.25,1.98,1.92,1.99,1.94
381,F1,2013-08-10,NaN,Bordeaux,Monaco,0.0,2.0,A,0.0,0.0,...,2.45,2.25,1.67,1.58,17.0,0.00,2.26,2.17,1.74,1.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
377,F1,2023-06-03,20:00,Paris SG,Clermont,2.0,3.0,A,2.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,F1,2023-06-03,20:00,Reims,Montpellier,1.0,3.0,A,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,F1,2023-06-03,20:00,Troyes,Lille,1.0,1.0,D,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
760,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1521,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN